### PR TITLE
Replaced boilerplate in setup.md with R setup

### LINKED ISSUE #11: "Setup" Page not configured correctly
The ["Setup" page](http://librarycarpentry.org/lc-r/setup.html) listed on the [main lesson menu](http://librarycarpentry.org/lc-r/index.html) still has placeholder text. I think this page should have instructions for downloading R and RStudio, correct?

### PR DESCRIPTION
**Pull request by annajiat**
Closes #11

Currently setup.md contains boilerplate for lesson maintainers, instead of R setup for learners.

Replaced that boilerplate.
Adapted R and R setup instruction from https://datacarpentry.org/R-ecology-lesson/#Install_R_and_RStudio

Thanks to @arieldeardorff

### CODE REVIEW

**Review by libjohn — APPROVED** [review]
update is designed to mimick HTML found here: https://datacarpentry.org/R-ecology-lesson/#Install_R_and_RStudio

The markdown is from here:  https://github.com/datacarpentry/R-ecology-lesson/blob/main/index.Rmd#L55

**Comment by arieldeardorff** [comment]
Hmm not sure this worked as the page is just one block of text: http://librarycarpentry.org/lc-r/setup.html

**Comment by libjohn** [comment]
Good catch @arieldeardorff .  There was some raw HTML in the markdown document that needed to be removed.  Please try it now.

**Comment by arieldeardorff** [comment]
Looks great now, thanks @libjohn!

**Pull request merged**
